[default]
SQLALCHEMY_TRACK_MODIFICATIONS = false
SQLALCHEMY_RECORD_QUERIES = true
AUTH0_DOMAIN = "the-crew-fsnd.us.auth0.com"
AUTH0_API_AUDIENCE = "thecrew-api"
AUTH0_ALGORITHMS = ['RS256']
MAIL_SERVER = "smtp.googlemail.com"
MAIL_PORT = 587
MAIL_USE_TLS = true
COMPRESS_MIMETYPES = [
    'text/html',
    'text/css',
    'application/json',
    'application/javascript'
]
COMPRESS_LEVEL = 6
COMPRESS_MIN_SIZE = 500
CACHE_TYPE = "redis"
CACHE_DEFAULT_TIMEOUT = 300
CACHE_KEY_PREFIX = "cache."
CACHE_REDIS_URL = "redis://localhost:6379/0"
THECREW_API_VERSION = "v1"
THECREW_DATE_FORMAT = "%Y-%m-%d"
THECREW_OBJECTS_PER_PAGE = 10
THECREW_LOG_TO_STDOUT = false
THECREW_ADMINS = ['filipebzerra@gmail.com']

[development]
SQLALCHEMY_DATABASE_URI = "@jinja sqlite:///{{'data-dev.sqlite' | abspath}}"

[testing]
TESTING = true
SQLALCHEMY_DATABASE_URI = "sqlite://"
AUTH0_GRANT_TYPE = "client_credentials"

[production]
