[default]
FLASK_APP = "thecrew.py"
SQLALCHEMY_TRACK_MODIFICATIONS = false
SQLALCHEMY_RECORD_QUERIES = true
AUTH0_DOMAIN = "the-crew-fsnd.us.auth0.com"
AUTH0_API_AUDIENCE = "thecrew-api"
AUTH0_ALGORITHMS = ['RS256']
AUTH0_CLIENT_ID = "ZqzyeEBInojE8HKbHC94gM5Sv2xFLRMI"
MAIL_SERVER = "smtp.googlemail.com"
MAIL_PORT = 587
MAIL_USE_TLS = true
COMPRESS_MIMETYPES = [
    'text/html',
    'text/css',
    'application/json',
    'application/javascript'
]
COMPRESS_LEVEL = 6
COMPRESS_MIN_SIZE = 500
CACHE_TYPE = "redis"
CACHE_DEFAULT_TIMEOUT = 300
CACHE_KEY_PREFIX = "cache."
THECREW_API_VERSION = "v1"
THECREW_DATE_FORMAT = "%Y-%m-%d"
THECREW_OBJECTS_PER_PAGE = 10
THECREW_LOG_TO_STDOUT = false
THECREW_ADMINS = ['filipebzerra@gmail.com']
FLASK_SECRET_KEY = "@format {env[FLASK_SECRET_KEY]}"
MAIL_USERNAME = "@format {env[MAIL_USERNAME]}"
MAIL_PASSWORD = "@format {env[MAIL_USERNAME]}"

[development]
SQLALCHEMY_DATABASE_URI = "@jinja sqlite:///{{'data-dev.sqlite' | abspath}}"
CACHE_REDIS_URL = "redis://localhost:6379/0"

[testing]
TESTING = true
SQLALCHEMY_DATABASE_URI = "sqlite://"
CACHE_REDIS_URL = "redis://localhost:6379/0"
AUTH0_GRANT_TYPE = "client_credentials"
AUTH0_CLIENT_ID = "nHaRDZC2Ro6Qvo2bnj58WmukR2UDHd4b"
AUTH0_CLIENT_SECRET = "@format {env[AUTH0_CLIENT_SECRET]}"

[production]
THECREW_LOG_TO_STDOUT = true
SQLALCHEMY_DATABASE_URI = "@format {env[DATABASE_URL]}"
CACHE_REDIS_URL = "@format {env[REDIS_URL]}"
